src/Sfs.EStore.Web.App/Areas/Retail/Controllers/DealerController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Sfs.Customers.Adapters.DataAccess.Entities;
using Sfs.EStore.Web.App.Areas.Retail.Models;
using Sfs.EStore.Web.App.Controllers;

namespace Sfs.EStore.Web.App.Areas.Retail.Controllers
{
    public class DealerController : ApplicationController
    {
        private readonly RetailModeDealerStore _retailModeDealerStore;
        private readonly NavisionContext _dbContext = new NavisionContext();

        public DealerController(RetailModeDealerStore retailModeDealerStore)
        {
            _retailModeDealerStore = retailModeDealerStore;
        }
        // GET: Retail/Dealer
        [HttpGet]
        public ActionResult Index()
        {
            Retail.Reset();

            return View();
        }

        [HttpGet]
        public Task<JsonResult> Get()
        {
            return Task.Factory.StartNew(() =>
            {
                using (_dbContext.Database.BeginTransaction(IsolationLevel.ReadUncommitted))
                {
                    return this.Json(_dbContext.Set<ContactUsername>().Where(x => x.Username == User.Identity.Name)
                        .Join(_dbContext.Set<ContactRelationship>(),
                            contactUser => contactUser.ContactNo,
                            contactRelation => contactRelation.ContactNo,
                            (contactRelation, contactUser) => contactUser).OrderBy(x => x.IsDefault)
                        .Join(_dbContext.Set<Customer>().Where(x => x.GlobalDimension1Code == "FGA"),
                            cus => cus.SourceNo,
                            contactUser => contactUser.No,
                            (cus, contactUser) => contactUser)

                        .Select(x => new Dealer { Name = x.Name.ToUpper() + " - " + x.City.ToUpper(), No = x.No })
                        .Distinct().ToList(), JsonRequestBehavior.AllowGet);

                }
            });
        }

        [HttpGet]
        public Task<JsonResult> GetDealer(DealerModel dealer)
        {
            return Task.Factory.StartNew(() =>
          {
              var returnModel = new DealerModel();

              returnModel.No = dealer.No;

              var _found = new string[] { "FIAT", "FIAT ABARTH", "FIAT PROFESSIONAL" };
              var _selectedForYou = new string[] { "ALFA ROMEO", "JEEP" };
              var _foundFranchise = new List<string>();
              var _selectedForYouFranchise = new List<string>();

              using (_dbContext.Database.BeginTransaction(IsolationLevel.ReadUncommitted))
              {
                  returnModel.Name = _dbContext.Set<Customer>().Where(x => x.No == dealer.No).Select(x => x.Name.ToUpper() + " - " + x.City.ToUpper()).FirstOrDefault();

                  _foundFranchise =
                     _dbContext.Set<Customer>().Where(x => x.No == dealer.No)
                         .Join(
                             _dbContext.Set<CustomerCampaign>()
                                 .Where(x => x.Type == 1 & _found.Contains(x.FranchiseCode)),
                             campaign => campaign.No,
                             cus => cus.CustomerNo, (campaign, cus) => cus)
                         .Select(x => x.FranchiseCode).Distinct().ToList();

                  _selectedForYouFranchise =
                   _dbContext.Set<Customer>().Where(x => x.No == dealer.No)
                          .Join(
                              _dbContext.Set<CustomerCampaign>()
                                  .Where(x => x.Type == 1 & _selectedForYou.Contains(x.FranchiseCode)),
                              campaign => campaign.No,
                              cus => cus.CustomerNo, (campaign, cus) => cus)
                          .Select(x => x.FranchiseCode).Distinct().ToList();

                  returnModel.FoundFranchises = _foundFranchise;
                  returnModel.SelectFranchises = _selectedForYouFranchise;
              }

              return this.Json(returnModel, JsonRequestBehavior.AllowGet);
          });
        }


        [HttpGet]
        public Task<JsonResult> ReturnDealer()
        {
            return Task.Factory.StartNew(() =>
            {
                return this.Json(RetailView.returnDealer(this.HttpContext), JsonRequestBehavior.AllowGet);

            });
        }
        
        [HttpPost]
        [Authorize]
        public void Setup(DealerModel dealer)
        {
            Retail.Load(dealer, User);
        }
    }
}

src/Sfs.EStore.Web.App/Areas/Retail/Views/Dealer/GetDealer.cshtml
<script type='text/javascript'>
    function submitForm() {
        document.forms.item(0).submit();
    }
</script>
@using (Html.BeginForm("ReturnMarkup", "Dealer", FormMethod.Post, new { id = "foundForm", @class = "form-horizontal" }))
{
    //if (@Model.FoundFranchises.Any())
    //{
        @Html.Hidden("Name", @Model.Name)
        @Html.Hidden("No", @Model.No)
        @Html.Hidden("Marquee", "found")

        <div class="row">
            {{dealer.FoundFranchises.length}}
            <div class="col-sm-8 alert alert-warning">
                <p><a href="#" id="submit-link" class="button" onclick="foundForm.submit();">Go to Retail Mode Set Up</a> <br />Found Marque showing for FIAT, FIAT ABRATH, FIAT PROFFESIONALS</p>
            </div><div class="col-sm-4"></div>
        </div>
    @*}*@
}

@using (Html.BeginForm("ReturnMarkup", "Dealer", FormMethod.Post, new { id = "selectForm", @class = "form-horizontal" }))
{
    //if (@Model.SelectFranchises.Any())
    //{
        @Html.Hidden("Name", @Model.Name)
        @Html.Hidden("No", @Model.No)
        @Html.Hidden("Marquee", "select")

        <div class="row">
            {{dealer.Name}}
            <div class="col-sm-8 alert alert-warning">
                <p><a href="#" id="submit-link" class="button" onclick="selectForm.submit();">Go to Retail Mode Set Up</a><br/>Select For You Marquee showing JEEP , ALFA ROMEO </p>
                @*<button type="submit" class="btn btn-info"><h3> Selected For You<br /></h3>@Html.Raw(string.Join("|", Model.SelectFranchises.Select(s => string.Format(" {0}", s))))</button>*@
            </div>
            @*<div class="col-sm-4"></div>*@
            @*<div class="col-sm-4"></div>*@
        </div>
    @*}*@
}

src/Sfs.EStore.Web.App/Areas/Retail/Views/Dealer/Index.cshtml
@using Cassette.Scripts
@using Sfs.EStore.Web.App.Models
@model Sfs.EStore.Web.App.Areas.Retail.Models.DealerListModel
@{

    ViewBag.Title = "Index";
    SetPageTitle("Select Dealer");
    SetBodyCssClass("markup");
    SetMetaData(new MetaDataModel
    {
        Title = "Dealer Setup"
    });
    Bundles.Reference<ScriptBundle>("~/areas/retail/scripts/apps/dealer");
}

<div ng-app="app" ng-controller="dealerController">
    <div class="row">
        <div class="col-sm-4">
            <select class="form-control" ng-options="dealer.No as dealer.Name for dealer in dealers track by dealer.No" ng-model="selectedDealer" ng-change="GetValue()" ng-selected="dealer.No == selectedDealer"></select>
        </div>
        <br />
        <br />
        <div class="col-sm-8">
            <div class="col-sm-8"></div>
        </div>
        <div class="row">

            <div class="col-sm-12 found-marque-dealer" ng-show="links.FoundFranchises.length" ng-click="Submit('found')">
                <br />
                <div class="col-sm-12 ">
                    <br /><p>Found Marque showing for FIAT, FIAT ABRATH, FIAT PROFFESIONALS</p>
                </div><div class="col-sm-12"></div>
            </div>

            <div class="col-sm-12 selected-marque-dealer" ng-show="links.SelectFranchises.length" ng-click="Submit('selected')">
                <br />
                <div class="col-sm-12 ">
                    <p>Select For You Marque showing JEEP , ALFA ROMEO</p>
                </div><div class="col-sm-12"></div>
            </div>
        </div>
        <div class="col-sm-8"></div>
    </div>

</div>